### ISSUE TITLE
docs: clarify (or remove) "zed" export statement from example in README

### ISSUE THREAD

**Issue by jsejcksn** [JakobJingleheimer/correct-ts-specifiers#1]
In [the before/after example shown in the README](https://github.com/JakobJingleheimer/correct-ts-specifiers/blob/d7129b10f46d89b61e5b5fbf68bed4803a7029c0/README.md?plain=1#L8-L34), there is an export related to "zed":

> Before:
> 
> ```ts
> import { PathLike } from 'node:path';
> import { Cat } from './Cat';
> import { baseUrl } from './config.js';
> 
> export { zed } from './zed';
> 
> export const makeLink = (path: PathLike) => (new URL(path, baseUrl)).href;
> 
> const cat = new Cat();
> ```
> 
> After:
> 
> ```ts
> import type { PathLike } from 'node:path';
> import { Cat } from './Cat.ts';
> import { baseUrl } from './config.js';
> 
> export type { Zed } from './zed.d.ts';
> 
> export const makeLink = (path: PathLike) => (new URL(path, baseUrl)).href;
> 
> const cat = new Cat();
> ```

In addition to being unused in the example code, the transformed export appears to be incorrect because the resulting statement uses a different name (`zed` → `Zed`). Is this just an issue with a manually-crafted documentation example, or would the codemod actually rename the export? If the former, perhaps it can just be removed from the example to increase signal-to-noise ratio. If the latter, perhaps it can be clarified: why is the export `zed` renamed to `Zed` during the transform?

**Comment by JakobJingleheimer** [comment]
Yes, thanks for catching the typo. It was manually crafted as a preliminary draft. I will replace these with the actual test and its output once ready.

The zed example is important because it covers 2 use-cases (a declaration file, and a `type` re-export) that require very specific support. This shows those are supported.

**Comment by jsejcksn** [comment]
Ref:

- https://github.com/JakobJingleheimer/correct-ts-specifiers/commit/f8b6534ad788fcd04240380514e62c2a517cf52e

**Comment by JakobJingleheimer** [comment]
> Ref:
> - https://github.com/JakobJingleheimer/correct-ts-specifiers/commit/f8b6534ad788fcd04240380514e62c2a517cf52e

Thanks! (Did the fix from my mobile)
